GET http://localhost:5000/skills


###

POST http://localhost:5000/skills
Content-Type: application/json

{
    "name": "TEST"
}   


###

PUT http://localhost:5000/skills/10
Content-Type: application/json

{
    "name":"ModifTEST"
}


###

DELETE  http://localhost:5000/skills/11


###

POST http://localhost:5000/wilders/34/skills/2


###

DELETE http://localhost:5000/wilders/32/skills/2