GET http://localhost:5000/wilders


###

POST http://localhost:5000/wilders
Content-Type: application/json

{
    "name": "TEST2",
    "city":"No man's land",
    "bio":"Unknown",
}   


###

PUT http://localhost:5000/wilders/68
Content-Type: application/json

{   
    "img":"https://i.imgur.com/LsW6TOb.jpg"
}


###

DELETE  http://localhost:5000/wilders/69


###

POST http://localhost:5000/wilders/68/skills/2


###

DELETE http://localhost:5000/wilders/68/skills/2