GET http://localhost:5000/wilders


###

POST http://localhost:5000/wilders
Content-Type: application/json

{
    "name": "Loulou"
}   


###

PUT http://localhost:5000/wilders/20
Content-Type: application/json

{   
    "city":"Bègles"
}


###

DELETE  http://localhost:5000/wilders/37


###

POST http://localhost:5000/wilders/34/skills/2


###

DELETE http://localhost:5000/wilders/34/skills/2