GET http://localhost:5000/wilders


###

GET http://localhost:5000/wilder/16


###

POST http://localhost:5000/wilders
Content-Type: application/json

{
    "name": "TEST2",
    "city":"No man's land",
    "bio":"Unknown",
}   


###

PUT http://localhost:5000/wilders/68
Content-Type: application/json

{   
    "bio":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam quis tellus pulvinar, imperdiet libero et, consequat orci. Fusce sit amet sapien turpis. Nullam pharetra, ligula non lobortis viverra, massa massa pulvinar purus, a hendrerit tortor nunc vel dui. Donec et gravida nulla. Sed vel erat faucibus, tincidunt nulla quis, pellentesque mauris."
}


###

DELETE  http://localhost:5000/wilders/69


###

POST http://localhost:5000/wilders/68/skills/2


###

DELETE http://localhost:5000/wilders/16/skills/8