GET http://localhost:3000/wilders


###

POST http://localhost:3000/wilders
Content-Type: application/json

{
    "name": "Loulou"
}   


###

PUT http://localhost:3000/wilders/16
Content-Type: application/json

{
    "name":"Grisch"
}


###

DELETE  http://localhost:3000/wilders/37


###

GET http://localhost:3000/skills


###

POST http://localhost:3000/skills
Content-Type: application/json

{
    "name": "JS"
}   


###

PUT http://localhost:3000/skills/1
Content-Type: application/json

{
    "name":"React"
}


###

DELETE  http://localhost:3000/skills/1


###

POST http://localhost:3000/wilders/29/skills/2
Content-Type: application/json
